### ISSUE TITLE
create-react-app fails to build with flow syntax in Picker.web

### ISSUE THREAD

**Issue by martnu** [react-native-picker/picker#100]
# Feature request

Would be great to get a dist-version of the web-version.

## Why it is needed

Just noticed my CRA-app which uses react-native-web fails due to the flow syntax in Picker.web.js

## Possible implementation

A build step when publishing?

**Comment by Zahoq** [comment]
Probably it's the same as:
https://github.com/react-native-picker/picker/issues/134#issuecomment-913818311

**Comment by d-vincent** [comment]
@martnu I have the same issue. Did you find a solution?
