### ISSUE TITLE
Dropdown icon disappears on Android when backgroundColor set

### ISSUE THREAD

**Issue by youn123** [react-native-picker/picker#112]
# Bug report

## Summary
Setting `backgroundColor` for `Picker` makes the dropdown icon disappear in android. 

## Environment info

`react-native info` output:

```bash
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 8.66 GB / 15.68 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 28, 30
      Build Tools: 28.0.3, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 1.6.5

## Steps to reproduce

```
<Picker style={{height: 50, width: '50%', alignSelf: 'center', color: '#FAFFFD' backgroundColor: '#393B41'}} />
```
Describe what you expected to happen:

The dropdown icon should not disappear.

**Comment by ubaldin** [comment]
Someone found a workaround ?

**Comment by sumithtexol** [comment]
You can set a container in the dropdown and remove the picker style and apply in the container 

`
<View style={reportStyle.pickerContainer}>
                            <Picker
                                <Picker.Item label=Category1 value=Category1>
                            </Picker>
                        </View>`

**Comment by snairsumith** [comment]
You can set a container in the dropdown and remove the picker style and apply in the container 

`
<View style={reportStyle.pickerContainer}>
                            <Picker
                                <Picker.Item label=Category1 value=Category1>
                            </Picker>
                        </View>`

**Comment by zibs** [comment]
Also wondering if this possible without any sort of workaround?

**Comment by snairsumith** [comment]
yes in my requirement it's working perfectly . Check the attachment 
<img width="550" alt="Screen Shot 2020-08-16 at 3 11 17 PM" src="https://user-images.githubusercontent.com/8740519/90331532-d6514d00-dfd2-11ea-93f2-4fd918cc5c9f.png">

**Comment by C-odes** [comment]
In my case, it disappears but also  does not actually add any background  color either  !

Documentation for this library should be better tbh.
