### ISSUE TITLE
[web] Empty labels on iOS + Unable to use in Expo's Snack

### ISSUE THREAD

**Issue by NiciusB** [react-native-picker/picker#113]
# Bug report

## Summary

Hi! I had an issue with this package after installing it to replace the deprecated `Picker` export from `react-native`.
![image](https://user-images.githubusercontent.com/2421121/87561308-c76a3880-c6bc-11ea-9741-302bd8ed7f21.png)

### iOS empty labels
It seems like the `label` prop is directly used as an attribute for `<option>`, instead of being inserted inside.
This still works on chrome desktop+android, but safari ios shows all labels as empty when you go to select one

### Unable to use in Expo's Snack
When I went to create a sample snack, it crashed. This is probably a bug in Snack or react-native-web, tho, so maybe it's not a concern for this library.
The error is:
```
Unable to resolve module 'react-native-web/dist/modules/UnimplementedView.js'
  Evaluating react-native-web/dist/modules/UnimplementedView.js
  Evaluating @react-native-community/picker.js
  Evaluating After.js
  Evaluating App.js
  Loading App.js
```

## Environment info

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 52.04 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5
```
`@react-native-community/picker 1.6.5`

## Reproducible sample code

```
import React from 'react';
import { Picker } from '@react-native-community/picker'

export default function App() {
  return (
      <Picker>
        <Picker.Item label="Goblet of Fire" value="globet" />
        <Picker.Item label="Order of the Phoenix" value="order" />
      </Picker>
  );
}
```

https://snack.expo.io/@niciusb/rnweb-picker-bug

**Comment by prasad456** [comment]
How to fix ?

**Comment by NiciusB** [comment]
@prasad456 Back then I went back to the `Picker` export from `react-native`, but they have apparently merged a fix for this already, so it should be fine now

**Comment by Naturalclar** [comment]
Thanks for raising the issue!
This should be fixed on latest expo sdk with latest react-native-picker version.
Snack can be found here
https://snack.expo.io/4MtW7Qbve
