### ISSUE TITLE
Disabling Font scaling on android

### ISSUE THREAD

**Issue by willnaoosmith** [react-native-picker/picker#130]
So, i'm using the below code to disable font scaling on my app, and everything goes well, except the Picker component. Is there a way to disable font scaling on this component?

code:

```
Text.defaultProps = {}
Text.defaultProps.allowFontScaling = false
Text.defaultProps.adjustsFontSizeToFit
```

**Comment by 29labs-wayne** [comment]
Picker not use react-native's Text

**Comment by willnaoosmith** [comment]
@29labs-wayne What does it use then?

**Comment by radhasoni65** [comment]
index.js file


import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
import {Text, TextInput} from 'react-native';

AppRegistry.registerComponent(appName, () => App);

//ADD this 
if (Text.defaultProps == null) {
    Text.defaultProps = {};
    Text.defaultProps.allowFontScaling = false;
}

if (TextInput.defaultProps == null) {
    TextInput.defaultProps = {};
    TextInput.defaultProps.allowFontScaling = false;
}




use these lines in your  index.js file. its works for me

**Comment by Devshail** [comment]
what to do with the Picke and Picker.Itme

**Comment by fionaw-ResDiary** [comment]
I'm also having this problem. Is there any way to disable font scaling for the Picker component (and Picker.Item)?

**Comment by coderdave** [comment]
@radhasoni65 this code does not work. Only affects `Text` and `TextInput` components.

**Comment by CostasCF** [comment]
Any solution? @coderdave
