### ISSUE TITLE
Picker web import line missing colon causing error

### ISSUE THREAD

**Issue by jeanjs** [react-native-picker/picker#134]
https://github.com/react-native-community/react-native-picker/blob/414892c0f633271a59216193d1f439bb6c0a1c96/js/Picker.web.js#L7

https://github.com/react-native-community/react-native-picker/blob/a50ec11d98b7cbb20b13892716ec9601852d9394/js/Picker.web.js#L13

**Comment by NateAGeek** [comment]
Any progress on this issue? Have you worked on a PR? If not, then I can take a look

**Comment by mkhib** [comment]
I also encountered this problem when compiling with react native web.
any fixes ?

SyntaxError: D:\RahtabMonoRepo\applications\node_modules\\@react-native-picker\picker\js\Picker.web.js: Unexpected token (9:12)

   7 | 
   8 | import React from 'react';
\>  9 | import type {
            |                    ^
  10 |   ViewStyleProp,
  11 |   TextStyleProp,
  12 | } from 'react-native/Libraries/StyleSheet/StyleSheet';

**Comment by mazor12** [comment]
> I also encountered this problem when compiling with react native web.
> any fixes ?
> 
> SyntaxError: D:\RahtabMonoRepo\applications\node_modules\@react-native-picker\picker\js\Picker.web.js: Unexpected token (9:12)
> 
> 7 |
> 8 | import React from 'react';
> > 9 | import type {
>       |                    ^
> 10 | ViewStyleProp,
> 11 | TextStyleProp,
> 12 | } from 'react-native/Libraries/StyleSheet/StyleSheet';

@mkhib 
I have the same issue 
any solution?

**Comment by mkhib** [comment]
> > I also encountered this problem when compiling with react native web.
> > any fixes ?
> > SyntaxError: D:\RahtabMonoRepo\applications\node_modules@react-native-picker\picker\js\Picker.web.js: Unexpected token (9:12)
> > 7 |
> > 8 | import React from 'react';
> > > 9 | import type {
> > >       |                    ^
> > > 10 | ViewStyleProp,
> > > 11 | TextStyleProp,
> > > 12 | } from 'react-native/Libraries/StyleSheet/StyleSheet';
> 
> @mkhib
> I have the same issue
> any solution?

As a temporary workaround I’ve created two separate components for web and native and used the deprecated picker from ‘react-native’ for the web and it is working as expected.

**Comment by Naturalclar** [comment]
I'm not able to reproduce this issue on my side.
Could you create a minimal sample repo that causes the issue? Thanks

**Comment by amitMist** [comment]
error - ./node_modules/@react-native-community/picker/js/Picker.web.js:9:12
Syntax error: Unexpected token

   7 | 
   8 | import React from 'react';
>  9 | import type {
     |             ^
  10 |   ViewStyleProp,
  11 |   TextStyleProp,
  12 | } from 'react-native/Libraries/StyleSheet/StyleSheet';

**Comment by danilrafiqi** [comment]
any update on this issue?

**Comment by sendyputra** [comment]
> any update on this issue?

after tested from latest version, just v1.9.5 work for me

**Comment by OkancanCosar** [comment]
v1.16.5
monorepo web + rn still has error

**Comment by alexandrasmith00** [comment]
I'm also encountering this error when using Picker inside of a typescript project: `

```
node_modules/@react-native-picker/picker/js/Picker.web.js: Unexpected token (10:12):
```
at this line:
```
import type {ViewProps} from 'react-native-web/src/exports/View/types';
```

using `1.16.5` of the picker

**Comment by Zahoq** [comment]
Hello @Naturalclar, please check minimal repo with repro:
https://github.com/Zahoq/rnwPickerIssue

to run app:
1. yarn
2. yarn web

Compilation attempt results with:
```
Failed to compile.

./node_modules/@react-native-community/picker/js/Picker.web.js
SyntaxError: C:\code\rnwPickerIssue\node_modules\@react-native-community\picker\js\Picker.web.js: Unexpected token (9:12)

   7 |
   8 | import React from 'react';
>  9 | import type {
     |             ^
  10 |   ViewStyleProp,
  11 |   TextStyleProp,
  12 | } from 'react-native/Libraries/StyleSheet/StyleSheet';
```

**Comment by d-vincent** [comment]
@Zahoq Same issue here, have you found any solution?

**Comment by Zahoq** [comment]
@d-vincent regarding workaround:
you can add webpack configuration to support flow:
```js
  addWebpackModuleRule({
    test: /react-native-(picker|web)(-select)?.*\.jsx?$/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          "@babel/preset-env",
          "@babel/preset-react",
          "@babel/preset-flow",
        ]
      }
    }
  }),
```

@Naturalclar fix works, thanks!
