### ISSUE TITLE
 Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker

### ISSUE THREAD

**Issue by vaibhav-navsoft** [react-native-picker/picker#143]
This issue still persist if i used community picker.
**#** Bug report

## Environment info

`react-native info` output:

```bash
# paste it here
```

Library version: x.x.x

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

**Comment by matijagrcic** [comment]
I've you're using nativebase then it will be fixed when this PR goes out https://github.com/GeekyAnts/NativeBase/pull/3230

**Comment by Naturalclar** [comment]
@vaibhav-navsoft There may be a file in your package that is using the Picker module from react-native (maybe NativeBase, as mentioned above.) please check which line the error is coming from.
