### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by RomanKwok** [react-native-picker/picker#145]
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef`.
    in Select (at Picker.web.js:61)

**Comment by Rocco970** [comment]
I'm having the same issue. Even creating a picker component with no props and no items in it triggers the warning. It does behave as expected, despite the warning.
 
I'm running expo 1.8.0 and the expected version range is stated to be 1.6.6 on startup, so this could be the source of the issue.

**Comment by itsarnavsingh** [comment]
I am seeing the same behavior.

**Comment by adeadavid** [comment]
Same error message keeps popping up when you use the picker component

**Comment by omuGen** [comment]
I have the same problem in a project using the latest expo/react-native SDK 39.0.3. I'm using Picker as a child element in a function component. I get the error with 1.6.6 (recommended by expo, see the post above by @Rocco970), as well as with version 1.8.1.

**Comment by ksi9302** [comment]
Same here.. on Expo 39.0.3 and picker 1.6.6

**Comment by scrapecoder** [comment]
getting same warning

`"@react-native-picker/picker": "^1.16.3"`
