### ISSUE TITLE
Picker.Item label cannot multiline?

### ISSUE THREAD

**Issue by 123artorux** [react-native-picker/picker#153]
Hi, i am new to react native. I am finding this component very helpfull but i am stuck at the moment.

I need to create a dropdown with multiple line. I am putting '\n' on picker.item label but it is readed as space. Is there is any way to insert a break line into the picker so the result would become multiline? Thank you.

**Comment by MOwais** [comment]
I am also looking for an answer to this

**Comment by BryanEnid** [comment]
Also me

**Comment by Naturalclar** [comment]
Added multiline support from `v1.10.0` :tada:

**Comment by michaelmaosynttro** [comment]
Does PickerIOS support this?

**Comment by tosebikan** [comment]
> Added multiline support from `v1.10.0` 🎉

this isn't available in the docs, how is it used

**Comment by donni106** [comment]
> Does PickerIOS support this?

there seems to be an open PR for that: https://github.com/react-native-picker/picker/pull/291

> > Added multiline support from `v1.10.0` 🎉
> 
> this isn't available in the docs, how is it used

i have also difficulties to achieve multiline behavior. i already asked on the PR that implemented the feature: https://github.com/react-native-picker/picker/pull/195

**Comment by abattlor** [comment]
> > Does PickerIOS support this?
> 
> there seems to be an open PR for that: #291
> 
> > > Added multiline support from `v1.10.0` tada
> > 
> > 
> > this isn't available in the docs, how is it used
> 
> i have also difficulties to achieve multiline behavior with expo. i already asked on the PR that implemented the feature: #195

Hi, we are using expo 40.0 and the v1.15.0 picker and we are facing the same issue on Android, can you guide me on the way to use it, we already have tried the following without success:

multiline={true}
numberOfLines={2}

Regards
