### ISSUE TITLE
Font size not applied on Android

### ISSUE THREAD

**Issue by capelski** [react-native-picker/picker#166]
The fontSize style parameter doesn't seem to work on Android. I can't manage to apply fontWeight or border properties either. They all do work well on web.

```jsx
<Picker
    onValueChange={/* ... */}
    selectedValue={/* ... */}
    style={{
        fontSize: 32,
        fontWeight: 'bold',
        borderColor: '#e2e2e2',
        borderWidth: 2,
    }}
>
     <Picker.Item label="Value 1" value="value_1" />
     <Picker.Item label="Value 2" value="value_2" />
</Picker>
```

**Comment by nihiluis** [comment]
I think you would need to use itemStyle here which is not supported on Android. I think you need to go into xml territory.

**Comment by capelski** [comment]
@nihiluis I'm using expo managed workflow, so I can't really go that deep unless I eject the project (which I want to avoid at all costs).

Is not exactly what I would call an elegant solution, but I will go with a style tweak to dodge this issue. Something like using a `position: absolute` react native Text or TextInput to display the selected value and keeping the Picker component to open a native modal picker with `opacity: 0`. Dirty yes, but working too.

```jsx
<View>
    <Text
        style={{
            // ...
            position: 'absolute'
        }}
    >
        {selectedValue}
    </Text>

    <Picker
        onValueChange={(value) =>
            //...
        }
        selectedValue={selectedValue}
        style={{ opacity: 0 }}
    >
        {/* ... */}
    </Picker>
</View>
```

I will still keep the issue open for now hoping somebody can extend further on why some style properties are not being applied.

**Comment by tim92109** [comment]
React was created to be cross-platform.  Therefore this component is not useful, should be considered non-compliant (and sloppy), and should be removed/replaced with something that can be used for both platforms.  I will just have to create a custom component since there is no real picker available for React at this time.

**Comment by capelski** [comment]
> React was created to be cross-platform. Therefore this component is not useful, should be considered non-compliant (and sloppy), and should be removed/replaced with something that can be used for both platforms. I will just have to create a custom component since there is no real picker available for React at this time.

@tim92109 I understand your anger, but there is no need to tag this project as **not useful** or **sloppy**. Just keep in mind this is an open source repository, so it's up to everyone to make it better.

**Comment by victorlmtavares** [comment]
Having the same issue here. Has anyone found a solution?

**Comment by capelski** [comment]
@victorlmtavares I ended up implementing a picker using React native modal. There isn't much logic in the component and you get to style it to suit your specific requirements.

The style tweak I suggested above doesn't work on iOS btw

**Comment by tim92109** [comment]
Sorry @capelski  i can't explain the amount of work i went through during the transition from expo sdk 32 to sdk 39. Month+ of unpaid work. No excuse though i know... Again sorry.

**Comment by tim92109** [comment]
Same solution i had (r n m). Was thinking about either asking react-native-modal owner/dev if i could reuse their code to save some time... Or better yet write some custom code to create the necessary incorporated modal. If i do that I'll share the git here. And might be nice to have collaborators or even co-authors is that's possible on gh @capelski

**Comment by capelski** [comment]
@tim92109 We could come up with a library that has React Native as a dependency and implements the picker in a similar way to the code below, allowing for full customization of any of the UI parts. That would be indeed cross-platform, but not a native implementation. As far as I know, (I've never created a React Native library), react native libraries use native platform components in order to be performant.

If you are thinking of creating a new native library, it will take you a lot of time and you will probably reach the same issue @nihiluis mentioned above.. If you are happy with this DIY approach instead, it's not worth creating a library. Create your own jsx/tsx component and reuse it all over your application (same I've ended up doing until react-native-picker supports this missing styling properties).

```typescript
import React, { useState } from 'react';
import {
    Image,
    Modal,
    ScrollView,
    Text,
    TextInput,
    TextInputProps,
    TouchableOpacity
} from 'react-native';
import caret from '../../assets/icons/caret.png';

type PickerOption = { label: string; value: string };

type PickerProps = {
    inputProps: TextInputProps;
    onValueChange?: (value: string) => void;
    optionRenderer?: (option: PickerOption) => JSX.Element;
    options: PickerOption[];
};

export const Picker: React.FC<PickerProps> = (props) => {
    const [isPickerActive, setIsPickerActive] = useState(false);

    const renderOption =
        props.optionRenderer ||
        ((option) => (
            <TouchableOpacity
                onPress={() => {
                    props.onValueChange && props.onValueChange(option.value);
                    setIsPickerActive(false);
                }}
                key={option.value}
            >
                <Text>{option.label}</Text>
            </TouchableOpacity>
        ));

    return (
        <React.Fragment>
            <TouchableOpacity
                onPress={() => {
                    setIsPickerActive(true);
                }}
            >
                <TextInput {...props.inputProps} />
            </TouchableOpacity>

            <Image
                height={16}
                source={caret}
                style={{
                    bottom: 10,
                    height: 16,
                    position: 'absolute',
                    resizeMode: 'contain',
                    right: 16,
                    width: 16
                }}
                width={16}
            />

            {isPickerActive && (
                <Modal>
                    <ScrollView
                        contentContainerStyle={{
                            flexGrow: 1
                        }}
                    >
                        {props.options.map(renderOption)}
                    </ScrollView>
                </Modal>
            )}
        </React.Fragment>
    );
};
```

**Comment by tim92109** [comment]
I see your point.  It would be nice but yes, I don't have that much time.  I'll just continue to use the custom component I created (basically the same as yours)...

`import React, {useState, useEffect} from 'react'
import {Text, View, ScrollView, StyleSheet, TouchableOpacity, SafeAreaView} from 'react-native'
import Modal from "react-native-modal"

const Entities = require('html-entities').AllHtmlEntities

const entities = new Entities()

const SimplePicker = (props) => {
	const [pickerOpen, setPickerOpen] = useState(false)
	const [valSelected, setValSelected] = useState()
	const [selectedLabel, setSelectedLabel] = useState()

	const [pickerOptions, setPickerOptions] = useState([])

	

	useEffect(() => {
		setPickerOpen(false)
		if (props.pickerItems) {
			buildItems(props)
		}
	}, [])

	useEffect(() => {
		
		if (valSelected) {
			setPickerOpen(false)
			
			props.setValue(valSelected, props.field)

			props.pickerItems.map((item) => {
				if (item.pickerValue == valSelected) {
					(props.field == "job") ? setSelectedLabel(item.pickerLabelJobName) : setSelectedLabel(item.pickerLabel)
				}
			})
		}
	}, [valSelected])

	const buildItems = (props) => {
		setPickerOptions([])
		
		if (props.field == "job") {

			props.pickerItems.map((option, key) => {
				
				key++
				(option.pickerValue && ((props.reportType == 1 && option.pickerLabelJobNumber.slice(0, 3) !== 'ACM') || (props.reportType == 2 && option.pickerLabelJobNumber.slice(0, 3) == 'ACM') || (props.reportType == 3))) && setPickerOptions(prev => [
					...prev, 
					<TouchableOpacity onPress={() => {setValSelected(option.pickerValue)}} key={key} style={styles.item}>
						<Text style={styles.itemText}>{entities.decode(option.pickerLabelJobNumber) + ' | ' + entities.decode(option.pickerLabelJobName)}</Text>
					</TouchableOpacity>
					]
				)
			})
		} else {

			props.pickerItems.map((option, key) => {
				key++
				(option.pickerValue) && setPickerOptions(prev => [
					...prev,
					<TouchableOpacity onPress={() => {setValSelected(option.pickerValue)}} key={key} style={styles.item}>
						<Text style={styles.itemText}>{entities.decode(option.pickerLabel)}</Text>
					</TouchableOpacity>
					]
				)
			})
		}
	}

	return (
		<View>
			<View style={styles.fieldRow}>
				{props.label && (<Text style={styles.pickerLabel}>{props.label}: </Text>)}
				<TouchableOpacity style={[styles.pickerStyle, props.pickerStyle]} onPress={() => setPickerOpen(true)}>
					{(props.value == '' || props.value == '0') ? ( //used to be '0' so I included it but maybe remove?
						<Text style={[props.pickerTextStyle, styles.pickerTextStyle]}>{props.placeholder}</Text>
					) : (
						<Text style={[props.pickerTextStyle, styles.pickerTextStyle]}>{entities.decode(selectedLabel)}</Text>
					)}

				</TouchableOpacity>
			</View>
			<Modal isVisible={pickerOpen}>
				<SafeAreaView style={styles.safeArea}>
					<ScrollView contentContainerStyle={styles.modalContainer}>
						{pickerOptions}
						<TouchableOpacity onPress={() => setPickerOpen(false)} key="0" style={styles.cancelModal}>
							<Text style={styles.cancelModalText}>Cancel</Text>
						</TouchableOpacity>
					</ScrollView>
				</SafeAreaView>
			</Modal>
		</View>

	)
}

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
	},
	fieldRow: {
		flexDirection: 'row',
		alignItems: 'center',
		alignContent: 'center',
		flex: 1,
		marginVertical: 10,
	},
	pickerLabel: {
		fontSize: 18,
		fontWeight: 'bold',
		flex: 2,
		textAlign: 'right',
	},
	pickerStyle: {
		backgroundColor: '#fff',
		borderBottomWidth: 2,
		borderColor: '#0000ff',
		paddingHorizontal: 10,
		paddingVertical: 3,
		flex: 3,
	},
	pickerTextStyle: {
		fontSize: 18,
		color: 'blue',
	},
	modalContainer: {
		backgroundColor: '#fff',
		borderRadius: 10,
		justifyContent: 'center',
		alignItems: 'center',
	},
	item: {
		paddingVertical: 5,
		marginTop: 10,
	},
	itemText: {
		fontSize: 20,
		color: '#0000ff',
	},
	cancelModal: {
		marginVertical: 15,
		paddingTop: 10,
		borderTopWidth: 1,
		borderTopColor: '#aaa',
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	cancelModalText: {
		fontSize: 20,
		color: '#ff0000',
	},
})

export default SimplePicker`

**Comment by billnbell** [comment]
Here is a patch

@react-native-picker+picker+1.9.10.patch


[@react-native-picker+picker+1.9.10.patch.zip](https://github.com/react-native-picker/picker/files/5935414/%40react-native-picker%2Bpicker%2B1.9.10.patch.zip)

**Comment by tim92109** [comment]
Nice!... yes, it would be nice to see it in the next update.

**Comment by MislavPeric** [comment]
Shouldn't this kinda be urgent? Can you fork your fix @billnbell?

**Comment by MislavPeric** [comment]
I've run into issues installing the patch saying that `package.json` is missing. Using patch-package

**Comment by billnbell** [comment]
Copy the patch into the patches directory, and unzip it

Add to your package.json:
   "postinstall": "patch-package"

**Comment by billnbell** [comment]
Forked: https://github.com/billnbell/picker/releases/tag/1.9.11

**Comment by MislavPeric** [comment]
@billnbell thanks a lot, you're the best

**Comment by tim92109** [comment]
Does this patch also fix the fontSize?  I don't see mention of it but I haven't tried it yet.

**Comment by billnbell** [comment]
It allows you to set fontFamily. fontSize would be another enhancement. But if you pick a fontFamily with size associated it will work for sure. We use MuseoSans-200 which is smaller than MuseoSans-500...

**Comment by tim92109** [comment]
@billnbell Makes it still relevant and still a fix... perfecto

**Comment by jsamr** [comment]
@billnbell Would you mind providing a PR?

**Comment by omatt** [comment]
font size in Android can be applied in Picker.Item style prop. I am on `"@react-native-picker/picker": "2.11.4"`

```
 <Picker>
    <Picker.Item style={{fontSize: 18}}/>
    // ...
</Picker>
```
