### ISSUE TITLE
'Picker' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by reggi** [react-native-picker/picker#171]
I am getting this typescirpt error :(

**Comment by kolobashek** [comment]
Same error. What did you do?

**Comment by connorlindsey** [comment]
Same error here with Typescript

**Comment by erdemgonul** [comment]
After wasting hours,  I found the solution.
Just add that into your package.json

```
"resolutions": {
  "@types/react": "17.0.2",
  "@types/react-dom": "17.0.2"
},
```

Credits:
[https://stackoverflow.com/a/71828113/8198997](https://stackoverflow.com/a/71828113/8198997)

**Comment by IAmCoder** [comment]
Instead of importing like this:
```
import Picker from '@react-native-picker/picker
```
Change the import to:

```
import { Picker } from '@react-native-picker/picker
```
Without the braces it expects `Picker` to be the default export.
