### ISSUE TITLE
itemStyle still not working on Android?????

### ISSUE THREAD

**Issue by jasenkabalac** [react-native-picker/picker#173]
I can't believe that we can't style Picker Item on Android for years. Is it that difficult to add at least font size prop ?????? 
Please do this !!

**Comment by DZuz14** [comment]
I totally agree. If a contributor could relay any information they have on why this hasn't been implemented, that would be great. Perhaps something tricky is going on that is hard to solve, idk, but I'd be glad to potentially look further into this for a solution. I could really use some text styling on Android.

Also, the down icon is super small, and can't be changed colors either. Pretty disappointing.

**Comment by dons20** [comment]
This really needs to be implemented. It's the only recommended picker for Expo and yet I can't style it properly on Android? 🤔

**Comment by billnbell** [comment]
see solution at https://github.com/react-native-picker/picker/issues/166

**Comment by dons20** [comment]
Great find! I need to test that out
