### ISSUE TITLE
Attempt to invoke virtual method 'android.view.Window android.app.Dialog.getWindow()' on a null object reference

### ISSUE THREAD

**Issue by wutiange** [react-native-picker/picker#181]
Attempt to invoke virtual method 'android.view.Window android.app.Dialog.getWindow()' on a null object reference

sentry 
![image](https://user-images.githubusercontent.com/43266613/100721705-a18ac980-33fa-11eb-8cfc-a41f6a9eda89.png)

"react-native-picker": "^4.3.7",
"react": "16.13.1",
"react-native": "0.63.3",

**Comment by wutiange** [comment]
不好意思，弄错了

**Comment by Deveshb15** [comment]
what was the issue?
