### ISSUE TITLE
app crash on items mapping

### ISSUE THREAD

**Issue by AnasAlamin** [react-native-picker/picker#198]
app crashes on items mapping 
it working on on web

to reproduce the error 

https://snack.expo.io/@anasalamin/picker

**Comment by jitendrahpatwa** [comment]
Seems this issue it was not showing in the web browser but in the device app expo client throws error and suddenly get crash. While gone through the documentation found  **"For Managed Workflow users using Expo 37
This component is not supported in the managed workflow for expo sdk 37. Please import the Picker from react-native."**
from, [https://github.com/react-native-picker/picker/issues/45#issuecomment-633163973](https://github.com/react-native-picker/picker/issues/45#issuecomment-633163973)
Therefore, finally need to use,
import { Picker } from 'react-native'.

**Comment by Naturalclar** [comment]
@AnasAlamin 

seems like you're mapping a number into label for Picker.Item
the label needs to be of type string.
Please try it with string, thanks!

**Comment by sampath1118** [comment]
> @AnasAlamin
> 
> seems like you're mapping a number into label for Picker.Item the label needs to be of type string. Please try it with string, thanks!

Thank you for your suggestion, my app is crashing because of i am mapping the array of numbers, thanks again and appreciated
