### ISSUE TITLE
Open the picker programmatically on Android

### ISSUE THREAD

**Issue by inspmoore** [react-native-picker/picker#204]
Would be amazing if the Android picker had a method to open/close it programmatically.
Something like:

```js
const picker = useRef()

return (
  <>
    <Button title="Open" onPress={()=> picker.current.open()} />
    <Picker ref={picker}>
       ...
    </Picker>
  </>
)
```

Without it's very hard to customize the UX. 

Cheers!

**Comment by mateusz1913** [comment]
@Naturalclar after focus events are available, I think it can be closed
