### ISSUE TITLE
Open/close android picker programmatically.

### ISSUE THREAD

**Issue by inspmoore** [react-native-picker/picker#205]
Would be amazing if the Android picker had a method to open/close it programmatically.
Something like:

```js
const picker = useRef()

return (
  <>
    <Button title="Open" onPress={()=> picker.current.open()} />
    <Picker ref={picker}>
       ...
    </Picker>
  </>
)
```

Without it's very hard to customize the UX. 

Cheers!

**Comment by darkerthanblackoff** [comment]
Try to use pickerRef.current.togglePicker(true)

**Comment by michaelypes** [comment]
Literally trying to do the same thing. I want to be able to launch the dialog on android from my own button and cant find a way to do this so it is adding an extra step for the user.

**Comment by VitamineC** [comment]
I know that is a bad solution, but as hotfix, it helps me:
(put opacity 0 picker over my button) 
`<Picker
          style={{
            height: 65,
            width: 120,
            position: 'absolute',
            right: 0,
            backgroundColor: 'black',
            opacity: 0,
          }}
        >
          <Picker.Item label="0" value="0" />
          <Picker.Item label="1" value="1" />
          <Picker.Item label="2" value="2" />
          <Picker.Item label="3" value="3" />
          <Picker.Item label="4" value="4" />
          <Picker.Item label="5" value="5" />
        </Picker>`

**Comment by michaelypes** [comment]
> I know that is a bad solution, but as hotfix, it helps me:
> (put opacity 0 picker over my button)
> `<Picker style={{ height: 65, width: 120, position: 'absolute', right: 0, backgroundColor: 'black', opacity: 0, }} > <Picker.Item label="0" value="0" /> <Picker.Item label="1" value="1" /> <Picker.Item label="2" value="2" /> <Picker.Item label="3" value="3" /> <Picker.Item label="4" value="4" /> <Picker.Item label="5" value="5" /> </Picker>`

How does that show the picker? I can't show the picker without clicking on the button that the component provides?

**Comment by mateusz1913** [comment]
@Naturalclar after focus events are available, I think it can be closed
