### ISSUE TITLE
Execution failed for task ':app:multiDexListDebug'.

### ISSUE THREAD

**Issue by AghaShayan123** [react-native-picker/picker#211]
I am facing this issue in

 What went wrong:
Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives:
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: com.reactnativecommunity.picker.BuildConfig

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by thuann-vn** [comment]
In my case, I already have @react-native-community/picker in package.json. I just remove it and everything works again.

**Comment by Einere** [comment]
this is because `@react-native-community/picker` in package.json. it duplicated with `@react-native-picker/picker`.
remove `@react-native-community/picker`.
