### ISSUE TITLE
Typescript: Static members cannot reference class type parameters

### ISSUE THREAD

**Issue by alpha0010** [react-native-picker/picker#216]
On version 1.9.11, I get the following error:
```
$  npx tsc
node_modules/@react-native-picker/picker/typings/Picker.d.ts:71:55 - error TS2302: Static members cannot reference class type parameters.

71      static Item: React.ComponentType<PickerItemProps<T>>;
                                                         ~


Found 1 error.
```

**Comment by kevinvangelder** [comment]
I am also experiencing this error.

**Comment by kevinvangelder** [comment]
Downgrading to 1.9.10 allows me to build. Maybe @Brumor has some ideas?

**Comment by konstantin-shkel** [comment]
Same for me TypeScript 3.8.3

**Comment by Brumor** [comment]
I guess T here on that line could be replaced with `ItemValue`, the goal of my PR was mostly to get `onValueChange?: (itemValue: T, itemIndex: number) => void;` to infer the right type for `itemValue`, but making that changes shouldn't break the original purpose of my PR;

Could any of you try changing the line to `static Item: React.ComponentType<PickerItemProps<ItemValue>>;` instead? If that works I'll make the fix!

**Comment by kevinvangelder** [comment]
@Brumor That worked for me locally, thanks!

**Comment by konstantin-shkel** [comment]
@Brumor That worked for me too.

**Comment by Brumor** [comment]
Created a PR for it: https://github.com/react-native-picker/picker/pull/222/files

**Comment by Naturalclar** [comment]
@Brumor thanks for the PR! merged and published :tada:

**Comment by professorkolik** [comment]
> Created a PR for it: https://github.com/react-native-picker/picker/pull/222/files
@Brumor @Naturalclar 

I think this PR is a hack rather than a fix, it breaks the reason of using TypeScript.

Can we revert this back to use Generic or if it's not the case then better use `any` instead
