### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNDateTimePicker

### ISSUE THREAD

**Issue by leofdias** [react-native-picker/picker#223]
I have this error when using the app by ios. On android it works normally. I'm using the expo

**Comment by guiac** [comment]
Same problem here. Were you able to find a solution?

**Comment by leofdias** [comment]
My problem was that I was using the 'native-base' library. They were causing conflict, so I just removed the 'native-base' from my project. Managed to solve??

**Comment by notjulian** [comment]
if you use `yarn` try this on `package.json`:

```
  "resolutions": {
    "@react-native-picker/picker": "1.16.1"
  }
```
