### ISSUE TITLE
Can't set dropdownIconColor to transparent after new release

### ISSUE THREAD

**Issue by LouisLoiseau** [react-native-picker/picker#235]
### Issue :
I updated the module with the latest version [1.13.1](https://github.com/react-native-picker/picker/releases/tag/v1.13.1) and found a regression in the operation of `dropdownIconColor`. The release was supposed to fix `dropdownIconColor` causing a crash when using string variables. It did but it appears that it has created an another issue. You can no longer set the value of this prop to transparent using hex or rgba.

**Comment by Naturalclar** [comment]
@LouisLoiseau So sorry about that, I'll take a look into it!

**Comment by LouisLoiseau** [comment]
Hey, sorry for the late answer, here's a screenshot. I think it's almost invisible due to the bright background but on this screenshot you can see that the "transparent" one is actually white.
<img width="40" alt="Capture d’écran 2021-04-02 à 20 15 32" src="https://user-images.githubusercontent.com/32438785/113442508-763bd980-93f0-11eb-977a-b7f0b7567e8c.png">

**Comment by C-odes** [comment]
...... is the documentation actually updated cuz it doesnt say use <Item> ....  Also for me dropDownIconColor doesnt affect anything

**Comment by wave2006** [comment]
I have a similar problem.

when I use dropdownIconColor and test with Expo on Android, it throw an error like below:
**Error while updating property 'dropdownIconColor' of a view managed by:RNCAndroidDialogPicker
java.lang.Double cannot be cast to java.lang.String**

code here:
`dropdownIconColor='#fb6a02'`

environment：
Expo SDK41
@react-native-picker/picker v1.15.0
Android app

**Comment by dj-doMains** [comment]
@wave2006 I am also getting this error

**Comment by LouisLoiseau** [comment]
Hey, here is another screenshot of the actual issue. On a high contrast picker you can see that the dropdown icon is white but should be transparent, as the dropdownIconColor prop is set to "#00000000". ![](https://i.imgur.com/xCbpm03.jpg)

**Comment by wave2006** [comment]
> @wave2006 I am also getting this error
> 
> If I roll back to version `1.31.0` it works fine.

thanks for you help! it's working now

**Comment by LouisLoiseau** [comment]
Any news on this issue ? Should i provide another example ?

**Comment by LouisLoiseau** [comment]
This code **should** make the dropdownIconColor transparent but it actually sets it **white** for every `<Picker>`.
```jsx
return (
  <Picker dropdownIconColor={'rgba(0, 0, 0, 0)'}>
      <Picker.Item label={'JS'} value={'javascript'} />
      <Picker.Item label={'RS'} value={'rust'} />
  </Picker>
  <Picker dropdownIconColor={'#00000000'}>
       <Picker.Item label={'JS'} value={'javascript'} />
       <Picker.Item label={'RS'} value={'rust'} />
  </Picker>
  <Picker dropdownIconColor={'transparent'}>
      <Picker.Item label={'JS'} value={'javascript'} />
      <Picker.Item label={'RS'} value={'rust'} />
  </Picker>
);
```
This issue is still happening on the latest version (1.16.1).

**Comment by LouisLoiseau** [comment]
Hello ! Thanks for the update. However i can't seem to make it work :(. I tried these lines : 

```javascript
<Picker dropdownIconColor={processColor('#00FFFF')}>
    <Picker.Item label={'JS'} value={'javascript'} />
    <Picker.Item label={'RS'} value={'rust'} />
</Picker>
```

But the dropdown icon color is not affected, it stays black.
Is it an issue ? Or did i do something wrong maybe ?

**Comment by 1280103995** [comment]
Still exists in 2.0.0.

**Comment by uloco** [comment]
Issue is still present in v2.1.0, please reopen.

**Comment by ceIia** [comment]
still exists in v2.2.0

**Comment by gmrcp** [comment]
stumbling into this issue in v2.4.0

**Comment by neuneed** [comment]
Still can't set to transparent in v2.4.8.

**Comment by alexdieudonne** [comment]
Still can't set to transparent in v2.4.8.
