### ISSUE TITLE
How to change the background color of the dialog for Android?

### ISSUE THREAD

**Issue by shamxeed** [react-native-picker/picker#244]

**Comment by javo222** [comment]
Did you find a solution to this?

**Comment by shamxeed** [comment]
> Did you find a solution to this?

Unfortunately no, as native modules doesn't always support all styling props. Had it been something like View element can be nested between the modal and the child elements then it can be archived by giving the View element flex: 1 and change the background color although that's not possible (nesting View) with this library.
