### ISSUE TITLE
Errors found on gradle build

### ISSUE THREAD

**Issue by kevin1choi** [react-native-picker/picker#264]
```
Errors found:

  C:\Users\kevin\Desktop\ProjectFF\ProjectFF\node_modules\@react-native-picker\picker\android\src\main\java\com\reactnativecommunity\picker\CheckedTextViewImpl.java:7: Error: This custom view should extend android.support.v7.widget.AppCompatCheckedTextView instead [AppCompatCustomView]
  public class CheckedTextViewImpl extends CheckedTextView {
                                           ~~~~~~~~~~~~~~~
  C:\Users\kevin\Desktop\ProjectFF\ProjectFF\node_modules\@react-native-picker\picker\android\src\main\java\com\reactnativecommunity\picker\TextViewImpl.java:7: Error: This custom view should extend android.support.v7.widget.AppCompatTextView instead [AppCompatCustomView]
  public class TextViewImpl extends TextView {
```

Hello, I am getting the above errors when running `gradle build`.

Please advise.

EDIT : 
  - Error occurs with Gradle 6.9 & 7.1 using picker v1.16.0.
  - Cannot test Gradle 7.2 at the moment due to errors with react-native-cli.

**Comment by kevin1choi** [comment]
No luck.

I don't have any problems running my app on the android emulator, however, so it's not super urgent for me as of yet.
I'll be digging into this further towards the end of next week.

**Comment by tatta** [comment]
did you find any solution?

**Comment by kevin1choi** [comment]
Am going to start working on it today. I'll post updates.

**Comment by kevin1choi** [comment]
So, I had read before that the error in question was just a warning but wanted to see if I could resolve it.
[](https://stackoverflow.com/questions/43246336/android-custom-view-should-extend-appcompattextview/43246399)

I couldn't find any solutions so I decided to just try building a release build and had no problems doing so.
I think I'll close this for now since it isn't blocking me any which way.

**Comment by hsuan1117** [comment]
Bad solution:
**ignore it!**
```shell
./gradlew build -x ':react-native-picker_picker:lint'
```
