### ISSUE TITLE
Caret / Dropdown Icon takes up too much space horizontally

### ISSUE THREAD

**Issue by KrisLau** [react-native-picker/picker#265]
It would be nice if there was a dropdownIconStyle prop to allow us to adjust the icon's styling.

**Comment by ricohumme** [comment]
I would be interested in this as well. In my design I need to push the caret more inwards, which is now not possible.

**Comment by KrisLau** [comment]
@ricohumme I ended up switching to https://github.com/hossein-zare/react-native-dropdown-picker
