### ISSUE TITLE
Can't select first option from Picker

### ISSUE THREAD

**Issue by MuhammadKaleem171** [react-native-picker/picker#267]
Can't select first option from Picker
code 
<Picker style={styles.dataBasePiker}
 dropdownIconColor="#21130d" 
 mode="dropdown"
  selectedValue={OnJoinColum}
  onValueChange={((itemValue, itemIndex)=>{
    setOnJoinColum(itemValue)
  })}>
    {
      ColumnName2.map(data=>{
        return(  <Picker.Item key={data.id} label={data.column} value={data.column} />)
      })
    }    
    </Picker>

**Comment by a2lop** [comment]
Any updates on this? for now I just added a not selectable first option like:
```
 <Picker
          ref={pickerRef}
          selectedValue={bookStatus}
          onValueChange={onChange}>
          <Picker.Item
            label={'Select an option:'}
            value={''}
            enabled={false}
          />
          {statuses.map((status) => (
            <Picker.Item
              key={status.value}
              label={status.label}
              value={status.value}
            />
          ))}
        </Picker>
```
But this is just a workaround, I don't want that first option

**Comment by koaladlt** [comment]
Yep, I'm having the same issue, if the user chooses the first option, it won't be selected

**Comment by babarmemon-dev** [comment]
any update on this?? i'm also facing same issue

**Comment by UmerAftabDev** [comment]
Hey i am having the same issue :( any fixes ?

**Comment by MuhammadKaleem171** [comment]
hey i found out solution don't know this is best or not .   
          <Picker style={styles.dataBasePiker}
      dropdownIconColor="#21130d" 
      mode="dropdown"
  selectedValue={SelectedDatabase}
  onValueChange={((itemValue, itemIndex)=>{
    setSelectedDatabase(itemValue)
    GetTabeName({itemValue})
  }
  )
  }>
           **<Picker.Item  label="Select Database " value="" color="#bdb9b9" /**>**
    {
      Database.map(data=>{
        return(  <Picker.Item key={data} label={data} value={data} />)
      })
    }
</Picker>
add item like "selecte price 0r product / anything  before maping a real data ... so your data start from index 1 .
you can see above  line start with **  .

**Comment by MuhammadKaleem171** [comment]
> 
> 
> Hey i am having the same issue :( any fixes ?

**Comment by mlecoq** [comment]
This issue is annoying since I do not want to add a header to my picker. Moreover, if a select another value, then I can select the first one
