### ISSUE TITLE
Picker like a modal in iOS ? 

### ISSUE THREAD

**Issue by dpetrelookiero** [react-native-picker/picker#270]
Hi, this is a question and not a bug.

It is possible to get this effect on iOS with this library ? 

![ex-ios](https://user-images.githubusercontent.com/83948921/119482733-815a1880-bd54-11eb-8077-21d7b2550c8b.gif)

I've tried with react-native-picker-select but unfortunately is outdated.

**Comment by JCameronP** [comment]
You can build a wrapper for the Picker that will display it like you want.

Just create a component that looks like a input (we used a `TouchableOpacity` wrapping a `Text` component).
Then, in that same component create a React Native Modal that contains the actual picker and a "Done" button to close the modal.

When the user clicks the input, it will open the `Modal` so the user can select with the actual `Picker` so they can make a selection. Just needs some simple state to display the selected text in the input and state to control whether the modal is showing or not.

**Comment by dpetrelookiero** [comment]
> You can build a wrapper for the Picker that will display it like you want.
> 
> Just create a component that looks like a input (we used a `TouchableOpacity` wrapping a `Text` component).
> Then, in that same component create a React Native Modal that contains the actual picker and a "Done" button to close the modal.
> 
> When the user clicks the input, it will open the `Modal` so the user can select with the actual `Picker` so they can make a selection. Just needs some simple state to display the selected text in the input and state to control whether the modal is showing or not.

thanks I was thinking the same workaround :)
