### ISSUE TITLE
Problem with open android picker. The screen is all dark.

### ISSUE THREAD

**Issue by rafaeljcunha** [react-native-picker/picker#274]
Problem with android picker oppened.

When I open the select, the picker has an almost transparent black background. It only happens on android. I can't change the background.

![Screenshot_2021-05-31-15-59-06-462_br com wine app dev](https://user-images.githubusercontent.com/47761691/120375786-905f3e80-c2f1-11eb-87a9-b0e7ab4a5448.jpg)

**Comment by rafaeljcunha** [comment]
This issue was related to the dark theme, from dark mode. The solution was to change in styles.xml:
###<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar"> ### to
###<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">###

**Comment by iamandiradu** [comment]
@rafaeljcunha That worked. 👍
