### ISSUE TITLE
Android build failed with error: method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by trandinhduc90** [react-native-picker/picker#279]
Hi everyone I got this error message when build android:  
"`error: method does not override or implement a method from a supertype @Override`" 
That the meter with ReactPickerManager.java file has two  `@Override` methods with the same name? When I remove one of them build will succeed. But I got a problem with CI/CD build system I cannot fix this error manually.

**Comment by gabrielew** [comment]
Same problem here
