### ISSUE TITLE
Picker does not work on Android 10 and 11

### ISSUE THREAD

**Issue by fedinabli05** [react-native-picker/picker#280]
I'm using this package for a project, the Picker works fine on IOS but does not show any text or can't even select smth from it on Android

**Comment by diegodcl** [comment]
I´m having the same problem. It shows the dropdown icon, but can`t open it.

**Comment by fedinabli05** [comment]
@diegodcl i tried it but stil doesn't work

**Comment by qasim483** [comment]
try giving it height or width in style prop.

**Comment by the-smart-home-maker** [comment]
giving it height and width works for me
