### ISSUE TITLE
Application closes on first click

### ISSUE THREAD

**Issue by osvaldokalvaitir** [react-native-picker/picker#282]
My app closes when I click the first time to open the modal, I'm using Android and I just made a new project with react-native 0.64.1 and @react-native-picker/picker 1.16.1.

The code that happens the error is simple, almost like the example:

```
import { Picker } from '@react-native-picker/picker';

const [selectedLanguage, setSelectedLanguage] = useState();

<Picker
        selectedValue={selectedLanguage}
        onValueChange={value => { setSelectedLanguage(value) }}
>
    <Picker.Item label="None" value={null} />
    <Picker.Item
        label="Test 1"
        value="399d6e60-cd18-11eb-b096-018576e7ab4f"
    />
    <Picker.Item
        label="Test 2"
        value="3ca02710-cd18-11eb-b096-018576e7ab4f"
    />
</Picker>
```

**Comment by Victor-Jansson** [comment]
Seems like the Android picker crashes if your selectedValue is not part of the Picker.Items. Try

`const [selectedLanguage, setSelectedLanguage] = useState(**null**); `

**Comment by osvaldokalvaitir** [comment]
if I'm not mistaken, I thought about it and tested it! but i will test again

**Comment by thecodecafe** [comment]
Hi, the same thing has been happening to me as well on Android, just noticed it yesterday.
My implementation is similar to that of @osvaldokalvaitir 
```
import { Picker } from '@react-native-picker/picker';

const [selectedLanguage, setSelectedLanguage] = useState(-1);

<Picker
        selectedValue={selectedLanguage}
        onValueChange={value => { setSelectedLanguage(value) }}
>
    <Picker.Item label="None" value={-1} />
    <Picker.Item
        label="Test 1"
        value="399d6e60-cd18-11eb-b096-018576e7ab4f"
    />
    <Picker.Item
        label="Test 2"
        value="3ca02710-cd18-11eb-b096-018576e7ab4f"
    />
</Picker>
```
The app just crashes and I get no error when this happens.

I use react native 0.64.1 and react-native-picker 1.16.3

**Comment by thecodecafe** [comment]
Hi @osvaldokalvaitir, I found the cause of the issue, it's our RN version, seems the issue was actually with react native, after updating from 0.64.1 to 0.64.2 the problem went away.
See this issue it's similar to this one.
https://github.com/react-native-picker/picker/issues/271

**Comment by osvaldokalvaitir** [comment]
@thecodecafe Hi, sorry for the delay, I won't be able to test it, I made my own component, so I will close the issue and test it in the future. Thanks.
