### ISSUE TITLE
HELP! android picker click issue

### ISSUE THREAD

**Issue by baesumin** [react-native-picker/picker#298]
1. simulator

<img src="https://user-images.githubusercontent.com/52240990/126315654-5cea0c7d-0013-4bab-93b8-78a5a3626b2d.png" width="300" height="600">

2. real device

<img src="https://user-images.githubusercontent.com/52240990/126315689-3284a11b-37e3-4e3f-9dcb-a98e307e44d8.jpg" width="300" height="600">

when i click 'picker', it gets dark in real device.
what should i do?

**Comment by Evokator** [comment]
Pretty sure I had a similar issue after updating RN. 
Changing the app theme seemed to fix it for me.
Go to styles in `res/values/styles.xml`. Change your app theme style to:
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

**Comment by baesumin** [comment]
> Pretty sure I had a similar issue after updating RN.
> Changing the app theme seemed to fix it for me.
> Go to styles in `res/values/styles.xml`. Change your app theme style to:
> `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`

thank you!!!
