### ISSUE TITLE
togglePicker() not working on android

### ISSUE THREAD

**Issue by tiennguyen9988** [react-native-picker/picker#323]
I need trigger open Picker from button. I used togglePicker and it's nice on ios but not working on android. Please help me any solution ?

**Comment by anishsundarjee** [comment]
You can toggle using the focus() and blur() methods provided by the picker library and use the useRef hook

`ref={refPicker}`
Add that to your picker

and create a function to toggle using 
`refPicker.current.focus()` to focus
`refPicker.current.blur()` to blur

hope this helps

**Comment by tiennguyen9988** [comment]
Thanks  anishsundarjee i tried this solution but it still doesn't work. I realized that it doesn't working on Android because version "@react-native-picker/picker packages is lower.
` "react-native-picker-select": {
      "version": "8.0.4",
      "requires": {
        "@react-native-picker/picker": "^1.8.3",
        "lodash.isequal": "^4.5.0"
      }
    },`
I'm trying to upgrade it to: 1.16.7. Do you have any solution?

**Comment by shalomTalker** [comment]
this solution work also i expo with web?
