### ISSUE TITLE
Picker with view alignItems center

### ISSUE THREAD

**Issue by paulobordignon** [react-native-picker/picker#325]
On React Native (0.64) Android using expo  (42.0.0):

`
<KeyboardAvoidingView style={styles.background} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>

    <View style={styles.container}>
        <Picker
        selectedValue="selecione"
        onValueChange={(itemValue, itemIndex) => setCategoryId(itemValue)}>
            <Picker.Item label="Java" value="java" />
            <Picker.Item label="JavaScript" value="js" />
        </Picker>
    </View>

</KeyboardAvoidingView>
`

`
background: {
    flex: 1,
    backgroundColor: colors.textLight,
},
container: {
    flex: 1,
    alignItems: 'center',
    marginTop: getStatusBarHeight() + 150,
    paddingTop: 50,
    backgroundColor: colors.background,
    borderRadius: 25,
},
`

Because alignItems: 'center' in container style, the picker hasn't working.

![2021-09-09_00-25](https://user-images.githubusercontent.com/24723164/132617471-096af10c-b436-4366-9ea3-cdb1ecd3147f.png)

**Comment by LuxikHS** [comment]
You have to change Picker width, because now is to big to render on screen.

**Comment by paulobordignon** [comment]
Thanks @LuxikHS

`
    style={{width: '90%'}}
`

It's the solution for my problem.
