### ISSUE TITLE
Picker.Item does not have a unique key.

### ISSUE THREAD

**Issue by lucaswitch** [react-native-picker/picker#358]
Given a picker: 

<Picker ...>
        {items.map(function (option, index) {
           <Picker.Item label={option.label} value={option} />
        })}
</Picker>
 Picker.Item does not have such option like key={} as react recommends.

**Comment by boerdjamin** [comment]
Sure it does, you can just add the `key` prop

**Comment by lucaswitch** [comment]
Yep, it does. Sorry.
Closing.
