### ISSUE TITLE
Is there a way to open the Picker programatically?

### ISSUE THREAD

**Issue by gianlop3z** [react-native-picker/picker#372]
Hello guys, i'm using the library, and i was trying to open the picker without rendering it, and after i read the docs i noticed you do not have a way to open the Picker modal **programatically**.

**Comment by a-eid** [comment]
you have to supply a ref & use it to open / close the picker 

it's stated in the readme.

**Comment by josh-thompson13** [comment]
I need a way to do this for other platforms not just Android, is there a way?

**Comment by saaspeter** [comment]
same problem, in ios, the blur method is not defined

**Comment by MohitNarkhede** [comment]
same problem

**Comment by emrahaydemir** [comment]
same problem
