### ISSUE TITLE
Release Not Triggered

### ISSUE THREAD

**Issue by marcod1419** [react-native-picker/picker#374]
Hi there! A little while ago, an important PR was merged that fixes an issue with newer `react-native-web` versions: https://github.com/react-native-picker/picker/pull/366

However, it looks like this was merged but unintentionally never released! So I was just wondering if a maintainer here could trigger the release so we can install the new update.

Thanks! And also thanks for your work on this project! 🙌

**Comment by DriesVS** [comment]
@marcod1419 had the same issue, since we have no response I went ahead and published a "fix" package, just to get a release out the door. I will unpublish the package later.

`"react-native-picker-picker-fix": "2.2.1"`

@Naturalclar Jesse, can you please start a release. Thanks!

**Comment by Naturalclar** [comment]
Sorry for the late reply.
Auto release is back in business and the fix should be released 😄
