### ISSUE TITLE
Windows ReactNativePicker DLL missing detailed file information/resources.

### ISSUE THREAD

**Issue by taenri** [react-native-picker/picker#443]
After the windows ReactNativePicker project is built, its DLL is missing file information such as "Product name" and "Product version". Certain rules in AppLocker can block DLLs that are missing this information (especially when using unpackaged applications), so it is important that this information is present. This means users running applications depending on ReactNativePicker.dll will be broken until the user manually whitelists the DLL on AppLocker.

A ReactNativePicker.rc file should be added so that the DLL file details are correctly populated at build-time.

**Comment by taenri** [comment]
PR Opened: https://github.com/react-native-picker/picker/pull/444

**Comment by Naturalclar** [comment]
Closed via #444
