### ISSUE TITLE
Use react-native-test-app for example

### ISSUE THREAD

**Issue by Naturalclar** [react-native-picker/picker#450]
I'd like to simplify the example directory by using https://github.com/microsoft/react-native-test-app

Replace the current example repository with a project created by `yarn test-init-app` (a command in react-native-test-app)

Follow the instruction in the react-native-test-app document to setup examples for iOS/Android/MacOS/Windows

**Comment by Cor4zon** [comment]
I can take that issue. Please assign it to me

**Comment by Naturalclar** [comment]
@Cor4zon Sure!

**Comment by Naturalclar** [comment]
Completed
