### ISSUE TITLE
ViewPropTypes is still being used

### ISSUE THREAD

**Issue by mikeRChambers610** [react-native-picker/picker#479]
In the latest Expo SDK versions 46 and 47, the new react-native is being used which deprecated the  ViewPropTypes. This react-native-picker tool is not updated to uses its own ViewPropTypes Component or deprecated prop types for time being.

This is not Picker tool is not working in 46 and 47 due to this.

**Comment by mikeRChambers610** [comment]
I realized I am supposed to be using Picker from React-Native if using managed workflow. Will reopen if any other issues.

Regardless, it is still using ViewPropTypes from React-Native which is deprecated.

**Comment by gabriellend** [comment]
I am use bare workflow and I am getting an error related to this so maybe don't close yet? It looks like this:
```
Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
```
`picker` is the only package I have that still uses it (from what I can see). This happened a couple weeks ago and then just mysteriously went away and now it's back again.
