### ISSUE TITLE
`focus` method on iOS

### ISSUE THREAD

**Issue by cubuspl42** [react-native-picker/picker#480]
The `focus` method, per the docs, works [only on Android](https://github.com/react-native-picker/picker#focus-android-only-lib-version-1160). Why is that?

Is there something tricky in this context on iOS? I'd be grateful for any hints, I'd like to submit a PR.

**Comment by DevOFVictory** [comment]
same issue here

**Comment by xmanemran** [comment]
I believable there is no support for `focus` in iOS. As the doc says 

> If you want to open/close picker programmatically on android (available from version 1.16.0+), pass ref to Picker:

https://github.com/react-native-picker/picker#usage

**Comment by karimkhamwani** [comment]
same here

**Comment by cubuspl42** [comment]
I'm closing this issue, as I'm no longer interested in such a method. What is more, with my current experience, I don't think that it was a good idea in the first place to name a method that opens a picker `focus`.
