### ISSUE TITLE
Border styles is not working

### ISSUE THREAD

**Issue by JpMayor1** [react-native-picker/picker#552]
I am styling Picker and the border is not working,
<Picker
style={{
width: "100%",
borderWidth: 1,
borderColor: Colors.dark,
}}
selectedValue={newGender}
onValueChange={(itemValue) =>
setNewGender(itemValue)
}
>
{genderOptions.map(
(genderOption, index) => (
<Picker.Item
key={index}
label={genderOption}
value={genderOption}
style={styles.text}
/>
)
)}
</Picker>

**Comment by TraFost** [comment]
do u find any solution?

**Comment by Ali-Aref** [comment]
any solutions ?
