### ISSUE TITLE
New version(2.7.0) compile time issue in android | Keeps app crashing

### ISSUE THREAD

**Issue by vinod1988** [react-native-picker/picker#555]
React native version = 0.70.14

compileOptions {
        sourceCompatibility JavaVersion.VERSION_18
        targetCompatibility JavaVersion.VERSION_18
    }

Stack trace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-picker_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-picker_picker:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)

ERROR  Invariant Violation: requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

This error is located at:
    in RNCAndroidDialogPicker
    in PickerAndroid (created by Picker)

**Comment by grnsmn** [comment]
Same problem here in my project

**Comment by grnsmn** [comment]
I've just tried to pin version to 2.6.0 and after this run android work for me
