### ISSUE TITLE
Facing Error when create debug app build: public record ReactPickerLocalData(int height) { ^ (use -source 16 or higher to enable records)

### ISSUE THREAD

**Issue by NaumanZafar007** [react-native-picker/picker#556]
Error Log: 
public record ReactPickerLocalData(int height) { ^ (use -source 16 or higher to enable records)

Code: 
package com.reactnativecommunity.picker; 
public record React Picker LocalDate(int height) { 
@Override public boolean equals(Object o) { 
if (this == o) return true; if (o == null || getClass() != o.getClass()) return false; ReactPickerLocalData that = (ReactPickerLocalData) o; return height == that.height; 
} 
@Override public String toString() { 
return "RectPickerLocalData{" + "height=" + height + '}'; 
} 
}

**Comment by tbc-usamabinishaq** [comment]
same issue

**Comment by hau1412** [comment]
same issue
