### ISSUE TITLE
Can't update selectedValue outside of Picker

### ISSUE THREAD

**Issue by zanaviska** [react-native-picker/picker#62]
# Bug

## Environment info
react-native: 0.60.5
Android 9

`react-native info` output:
OS macOS Mojave 10.14.6
Node13.8.0
Npm 6.13.7

## Steps To Reproduce

Create empty project with Picker and some button(timeout) that should change selectedValue

Describe what you expected to happen:

selectedValue is changed

## Reproducible sample code
Some code pasted here(to run switch to android) https://snack.expo.io/BkB184II8

**Comment by jainkuniya** [comment]
Hi @zanaviska 

You should use 
```
componentDidMount() {
    setTimeout(() => this.setState({selectedValue: "2019"}, () => console.warn(`I've updated`)), 1000);
  }
```

**Note:** "2019"

**Comment by mertbekci** [comment]
Can you try this line ?

`            selectedValue={this.state.selectedValue.toString()}
`

**Comment by zanaviska** [comment]
Issue has been fixed back into May 10, 2020 thanks to @jainkuniya, just I forget to close issue

**Comment by GuilhermeZanetti** [comment]
Im having this error but with React Hooks....
