### ISSUE TITLE
[Feature Request] expect Picker in Android to have the same behavior with iOS

### ISSUE THREAD

**Issue by KingAmo** [react-native-picker/picker#65]
# Feature Request

## Why it is needed
in Android,  Picker use `spinner` which is too ugly, could it possible it has the same behavior in iOS?  

## Possible implementation
maybe we can wrap https://github.com/AigeStudio/WheelPicker in android ?

**Comment by musicode** [comment]
@KingAmo 
maybe [picker](https://github.com/react-native-hero/picker) is what you want.

**Comment by KingAmo** [comment]
> @KingAmo
> maybe [picker](https://github.com/react-native-hero/picker) is what you want.

nice work, i'll have a try

**Comment by Naturalclar** [comment]
Thanks for raising the issue! However, I believe the purpose of this library is to "provide native experience in each os" .
Providing same behavior in all OS won't meet the purpose.
Closing the issue for triaging purpose.
