### ISSUE TITLE
Android styles

### ISSUE THREAD

**Issue by ArekChr** [react-native-picker/picker#73]
Setting styles on android device is the biggest disaster

**Comment by jainkuniya** [comment]
hey @ArekChr can you please share more information, what you mean by `biggest disaster` and what is your expected behaviour.

**Comment by bfraiman** [comment]
Please check this example --> https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949

**Comment by ArekChr** [comment]
I mean this should be possible to do inside react component, jsx.
not like here -> https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949

**Comment by LeonDong199509** [comment]
Does anyone know how to change the popup background dynamically? I need to implement dark mode for my app, but I cannot change the background color  dynamically. The method on stackoverflow above can only set a fixed background color.

**Comment by ArekChr** [comment]
> Does anyone know how to change the popup background dynamically? I need to implement dark mode for my app, but I cannot change the background color dynamically. The method on stackoverflow above can only set a fixed background color.

it's impossible

**Comment by Biplovkumar** [comment]
> > Does anyone know how to change the popup background dynamically? I need to implement dark mode for my app, but I cannot change the background color dynamically. The method on stackoverflow above can only set a fixed background color.
> 
> it's impossible

Plz suggest what should we do  ?

**Comment by ArekChr** [comment]
> > > Does anyone know how to change the popup background dynamically? I need to implement dark mode for my app, but I cannot change the background color dynamically. The method on stackoverflow above can only set a fixed background color.
> > 
> > 
> > it's impossible
> 
> Plz suggest what should we do ?

The same behavior like on iOS. dark/light mode doesn't supported on android and can't change it dynamically

**Comment by hadnet** [comment]
Why in hell we can't change de background color of the Android picker (both dialog/dropdown prop) on RN?? Is it so difficult? This is ridiculous, seriously!

**Comment by ryanbabbly** [comment]
This stackoverflow post is linked everywhere regarding this issue: https://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker/39141949#39141949 but it doesn't work for me at all whether I import from this library or right from 'react-native'.

This is my styles.xml:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- styles for android react native picker -->
    <item name="android:spinnerStyle">@style/spinnerTextStyle</item>
    <item name="android:spinnerItemStyle">@style/spinnerTextStyle</item>
    <item name="android:spinnerDropDownItemStyle">@style/spinnerTextStyle</item>
  </style>

  <style name="spinnerTextStyle" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:fontFamily">@font/merriweather_family</item>
    <item name="android:textSize">12dp</item>
  </style>
```

I don't even want to do anything complicated but it doesn't work. No matter what I try.

**Comment by russeg** [comment]
> The same behavior like on iOS. dark/light mode doesn't supported on android and can't change it dynamically

That's right. I have to roll my own non native picker. It's not native looking already because of React Navigation.

Might as well use Flutter since it has a more consistent user interface, than my weird looking app with my native/non native components 😞

**Comment by hugotox** [comment]
any docs on this? I tried the example from https://github.com/react-native-picker/picker/pull/233/files#diff-12f76272c0ab68693fac6a6a5c943434480858eeac4ca45cec588bbda23efd46R21 but styles aren't applied

**Comment by JenilynnB** [comment]
I've also tried the example on both the emulator and real device and styles aren't applied on either. Any help here?

**Comment by codyweis** [comment]
Styles work if applied individually to a Picker.Item, however you dynamically set the items with an array.map, the style wont be applied to the returned <Picker.Item...

**Comment by afonsopbarros** [comment]
Not working

**Comment by jimbali** [comment]
It works fine. Thanks!

```
<Picker.Item style={{ backgroundColor: 'red', color: 'blue' }} key="Blah" label="Blah" value="Blah" />
```
